# Generated by Django 4.0.8 on 2023-01-20 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_id_userprofile_puuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Puuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
