# Generated by Django 4.0.8 on 2023-01-19 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business'),
        ),
    ]
