# Generated by Django 4.0.8 on 2023-01-20 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0009_alter_product_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Mens Body wears'), ('2', 'Women Body wears'), ('3', 'Unisex Body wears'), ('4', 'Educational'), ('5', 'Sports'), ('6', 'Food'), ('7', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='business.product'),
        ),
        migrations.CreateModel(
            name='ServiceBusiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ProfilePix', models.ImageField(blank=True, upload_to='ServiceBuzProfile/')),
                ('description', models.TextField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='ServicePix/')),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('1', 'Educational'), ('2', 'Sports'), ('3', 'Food'), ('4', 'Cleaning'), ('5', 'Others')], default='Others', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='business.servicebusiness')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='business.service'),
        ),
    ]
